### ISSUE TITLE
bossac fails on on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by gdsports** [sparkfun/Arduino_Boards#33]
The fix for #32 does is not sufficient for 14.04. I guess bossac should be built so it does not depend on shared libraries. Or it should be compiled on Ubuntu 14.04. bossac 1.7.0 included with the Arduino SAMD board package works on 14.04 on Adafruit m0 boards but does not work on the SparkFun samd21 mini.

```
/home/me/ardtmp/arduino-1.8.5-m0/portable/packages/SparkFun/tools/bossac/1.4.0/bossac -i -d --port=ttyACM1 -U true -i -e -w -v /tmp/arduino_build_43069/Blink.ino.bin -R 
/home/me/ardtmp/arduino-1.8.5-m0/portable/packages/SparkFun/tools/bossac/1.4.0/bossac: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/me/ardtmp/arduino-1.8.5-m0/portable/packages/SparkFun/tools/bossac/1.4.0/bossac)
/home/me/ardtmp/arduino-1.8.5-m0/portable/packages/SparkFun/tools/bossac/1.4.0/bossac: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/me/ardtmp/arduino-1.8.5-m0/portable/packages/SparkFun/tools/bossac/1.4.0/bossac)
An error occurred while uploading the sketch
```

**Comment by jimblom** [comment]
We just pushed an update to the samd packages (1.5.0) that should hopefully resolve this issue.

Instead of directly supplying (an outdated version of) bossac, the new package relies on Arduino's SAMD tools (including OpenOCD, armgcc, CMSIS, and bossac). This seems to resolve the issue on my Ubuntu machine.

@gdsports -- Thanks for pointing this out to us! Sorry it took so long to address it. Please feel free to re-open the issue if you have any more trouble.
