### ISSUE TITLE
Unable to install the Blynk board

### ISSUE THREAD

**Issue by cmfrancis** [sparkfun/Arduino_Boards#48]
`"url": "http://arduino.esp8266.com/win32-xtensa-lx106-elf-gb404fb9-2.tar.gz"` 
found in our JSON file returns a 404 and that breaks the ability to add the Blynk board to the IDE.

**Comment by bboyho** [comment]
It looks like the server/domain name possibly changed on ESP8266's side? Older issues filed on the ESP8266 core for Arduino seems to indicate that that was the issue. User's will see this in the Arduino Boards Manager:

    Error downloading http://arduino.esp8266.com/win32-xtensa-lx106-elf-gb404fb9-2.tar.gz

Removing the download linked to to repo for the ESP8266 .json and it looks like something was updated about 22 days ago? Maybe we can update our files and update links based on this part of the .json file:

[https://github.com/esp8266/esp8266.github.io/blob/master/stable/package_esp8266com_index.json#L1080](https://github.com/esp8266/esp8266.github.io/blob/master/stable/package_esp8266com_index.json#L1080)

**Comment by thirtytwobits** [comment]
Still seeing this issue. I can't develop against my blynk board right now.

**Comment by djboby72** [comment]
There is a problem in the json file, so the file
win32-xtensa-lx106-elf-gb404fb9-2.tar.gz
can not be downloaded.
You can change the json file by replacing the path
http://arduino.esp8266.com/
with
https://github.com/esp8266/Arduino/releases/download/2.3.0/
or you can use my modified file to add the Sparkfun BlynkBoard in arduino. But beware of the removal of generic support esp8266 if it is already installed because it is incompatible with Sparkfun BlynkBoard.
http://djboby.com/download/package_sparkfun_github_index.json

**Comment by santaimpersonator** [comment]
You can only install either the generic esp8266 board definitions or SparkFun's esp8266 board definitions. Installing both board definitions cause a file path conflict since the SparkFun Thing Dev is named in both packages. (**Issue may include other ESP8266 board definitions.**)

I tested this on a few systems (Windows and Mac) and sometimes both folders are included, but other times the folders get overwritten by the new board definitions. Overall, the Arduino IDE is only able to see one of the board definition folders (or package) in either situation.

I created a [pdf with instructions](https://github.com/sparkfun/Arduino_Boards/files/3413135/Blynk-.Community.ESP8266.Boards.pdf) for a teacher, a few months back, to remove all definitions and only install SparkFun's board definitions to work around the issue. (*Sorry, I haven't had the time to update the tutorial. I hope this solves a majority of the issues; any feedback on whether this works is appreciated.*)

**Comment by edspark** [comment]
We've updated our Arduino boards JSON file to fix the problematic link, update to 2.1.1 for the latest: 
![image](https://user-images.githubusercontent.com/18684691/67891450-3d6f4500-fb18-11e9-9b9e-601f106789b7.png).

**Comment by bboyho** [comment]
@edspark updated the url and we were able to download the board definitions! Were were able to get **blink.ino** and **BlynkBoard_Core_Firmware** to upload with ESP8266.

**Comment by edspark** [comment]
@santaimpersonator I've opened a seperate [issue](https://github.com/sparkfun/Arduino_Boards/issues/55) since this particular behavior is separate from the original issue.

**Comment by bboyho** [comment]
For those that are interested, @edspark worked with espressif to include the board in the [ESP8266 Arduino add-on [v2.6.0] ](https://github.com/esp8266/Arduino/releases/tag/2.6.0). We'll be updating the documentation as well.

🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
