### ISSUE TITLE
ESP32 - wish you would sync up to current Espressif ESP32 release

### ISSUE THREAD

**Issue by KurtE** [sparkfun/Arduino_Boards#97]
The newer releases have additional capabilities and libraries, such as LittleFS.

**Comment by santaimpersonator** [comment]
We have since handed over maintenance of the Arduino core for our ESP line of microcontroller products, over to Espressif Arduino core. This was primarily due to changes in the Arduino IDE that caused conflicts in the compilation for MCUs hosted by separate parties.

Please, use their Arduino core for the latest and greatest. Please refer to this tutorial for [installation instructions for third-party Arduino cores](https://learn.sparkfun.com/tutorials/installing-board-definitions-in-the-arduino-ide/installing-a-third-party-board-definition).
